### ISSUE TITLE
Change product thumbnail, update variant select.

### ISSUE THREAD

**Issue by addedlovely** [Shopify/Timber#232]
Thanks for the update to make changing the variant update the product image. Is it possible to implement the reverse, so that when selecting a thumbnail the variant select updates.

Only working one way is confusing for users.

Thanks

Ian.

**Comment by mikcole** [comment]
Awesome, glad I found this thread. Super easy and clean to implement using a snippet.

Great functionality.

thanks!

**Comment by iltempovola** [comment]
Hi guys, I have set up my shop about a week ago and this is an issue for me too. I suggest this gets prioritized in Timber. Thanks Caroline for the temp code!

**Comment by nisha0123** [comment]
Hi guys, I am using that code in GRID Theme ( https://themes.shopify.com/themes/grid/styles/minimal ) but it is not working in this theme. Can you help me for this issue? let me know if you want to site link?
Thanks!

**Comment by carolineschnapp** [comment]
You will need to contact Pixel Union about this @nisha0123 The piece of code I provide may or may not work for you depending on your theme's HTML. You theme does not use the Timber framework.

**Comment by addedlovely** [comment]
@carolineschnapp why has this been closed, it's still not resolved in Timber?

**Comment by carolineschnapp** [comment]
The decision has been made to not include this feature in any Shopify theme for now @addedlovely. It's not impossible that this changes in the future. 

It's unfortunate this issue here attracts comments from people who are not using the Timber framework, it's my fault, I should not have added a link to a non-Timber snippet here.

**Comment by addedlovely** [comment]
@carolineschnapp thanks for the update! Yeah "off topics" must be a right pain.

**Comment by RMKama** [comment]
@carolineschnapp THANK YOU! Finding your solution for this has absolutely made my day.

**Comment by nisha0123** [comment]
You means it is not possible in my site?

**Comment by carolineschnapp** [comment]
With the help of a designer or developer, rest assured that almost everything is possible in Shopify, so this function can surely be added to your theme. I am not able to tell you if my code snippet will work 'as is' in your theme or not, though. 

This issue is about Timber, so I would invite you again to reach out to Pixel Union who supports your theme. You can also post your questions in the Shopify forums in the _Design_ category: https://ecommerce.shopify.com/c/ecommerce-design 

Thanks for keeping this on-topic @nisha0123 ! Just so that you know every time you post a comment here, everyone who's contributed to this issue gets a notification.

**Comment by Eyewebmaster** [comment]
This issues is not yet fix by Shopify. They had variants samples that you can use but their information is not complete. We've been working with this store http://www.thesmoothshop.com and work out with the filters. Now we're working on this variant auto color select.

**Comment by Rastikoy** [comment]
Hello Shopify masters, 
I know this thread is very old . 
I'm currently working on a Shopify project, Now all i want is to modified the product page, and i want   the idea of this site > @addedlovely  samples > http://shop.carhartt-wip.com/gb/men/sweats/sweatshirts/I015897/hooded-chase-sweatshirt .
anyone can help me to achieve this ? thanks in advance .
