### ISSUE TITLE
Currency Switcher support in ajax cart modal

### ISSUE THREAD

**Issue by dougalcrowder** [Shopify/Timber#251]
Hi, trying to implement this http://docs.shopify.com/manual/configuration/store-customization/currencies-and-translations/currencies/how-to-show-multiple-currencies on Timber. It works everywhere except the Ajax cart. I realise this is probably more of a feature request, but, thought I would ask anyway...

**Comment by plankguy** [comment]
If anyone is wondering, I got this working calling the ``Currency.convertAll()`` method within a ``ajaxComplete`` handler in the *currencies.liquid* snippet outlined in the above manual entry:

````
{% if settings.ajax_cart %}
    /* Update ajax cart with currency */
    $(document).ajaxComplete(function() {
        Currency.convertAll(defaultCurrency, Currency.currentCurrency);
        if( Currency.currentCurrency !== defaultCurrency ) {
            jQuery('._currencyNote').show();
            jQuery('._selectedCurrency').text(Currency.currentCurrency);
        } else {
            jQuery('._currencyNote').hide();
        }
    });
{% endif %}
````
I'm also show/hiding a currency note/explanation. There's likely a more elegant solution, but this does the job!

**Comment by lesterdefreitas** [comment]
Having same issue. Would be good to have an all-round solution.

Question: Where exactly should this code be placed in the currencies.liquid file?

**Comment by cshold** [comment]
In the latest version of Timber you can bind to an event after the cart markup has loaded. 
```
jQuery('body').on('ajaxCart.afterCartLoad', function(evt, cart) {
  // Run any JS you need here
});
```
This can be called from anywhere, giving you the most flexibility to use custom JS with the ajax cart.

**Comment by lesterdefreitas** [comment]
Thanks Carson,

We dealing specifically with the new Brooklyn theme, and can't get this issue solved. The only we have found is to force a page refresh on a currency change so that the AJAX cart also refreshes. A little but rudimentary though, we would like a better solution.

**Comment by cshold** [comment]
I'm assuming the issue is that the cart elements haven't loaded on the page for jQuery to get a hold of the proper selectors, so when you switch the currency it does its best to update all prices it knows about — but missing the recently added ajax cart ones.

With the snippet from my last comment, you should re-initialize the currency switcher JS. This will be dependant on your implementation of it so I can't speak with exact details. By reinitializing it, the proper selectors will be read and updated without a page refresh.
