### ISSUE TITLE
Timber, Ajax cart and multiple currency problem

### ISSUE THREAD

**Issue by mikcole** [Shopify/Timber#330]
Setup multiple currency on Timber 2.01 based site with an Ajax cart and it has bugs as the currency changes as items added to cart.

**Non Ajax cart works fine.**

Here is a Timber 2.02 theme with no modifications (except for the multiple currency with two currencies) for an example:

kutenaiclothing-responsive.myshopify.com  pswd:brahst

**Comment by cshold** [comment]
This is part of a known issue and is tracked here https://github.com/Shopify/Timber/issues/244

The multiple currency javascript doesn't run each time the cart is shown, so you'll have to manually initialize it again. You can do this in the `onToggleCallback` function provided by Timber's ajax cart ([view options](http://shopify.github.io/Timber/#ajax-cart)).

Because of the bug, however, you may need to add a slight `setTimeout` to make it work as expected. Either way, there will be some manual work you'll have to do.
