### ISSUE TITLE
Having different layouts for cart.liquid and ajax-cart-template.liquid - Timber

### ISSUE THREAD

**Issue by spring-91** [Shopify/Timber#350]
Hi there, 

I was directed here by Shopify theme support. I’m wondering if you could help me with a problem I’m facing with the Ajaxify cart for my theme using the Timber framework.

My design has a slightly different layout of content between my standard cart page (cart.liquid template) and the ajaxify pop-out quick cart that I want to create. I’m a bit confused as to how you remove & add certain elements, for example when I move the product title to go above my product image nothing changes…

Am I right in thinking that the ajaxify script is pulling in the /cart form content from the cart.liquid template, if so am I able to create an additional different form in a template for my ajax quick cart?

Are you able to explain how to achieve this? It is possible to have a different layout between the cart and the quick cart?

Thanks in advance!

**Comment by cshold** [comment]
You can use `snippets/ajax-cart-template.liquid` for an alternative layout if you'd like. In our next version of the cart we're actually moving to that method as well.

At the bottom of your `theme.liquid` layout file, change the `useCartTemplate` parameter to `false`. When true, it'll use your `cart.liquid` template. When false, it'll use `ajax-cart-template.liquid`.

**Comment by spring-91** [comment]
Thanks Carson, that worked a treat. However I'm getting a slight issue with a couple of outputs by doing that. On both the {{price}} and {{totalPrice}} its outputting a <span class="money"> around the value in the browser, so what I'm seeing in the actual browser is 'Total:<span class="money">£60.00</span>' instead of just 'Total: £60.00'. Any ideas why this is happening?

**Comment by spring-91** [comment]
Thanks Carson, that worked a treat. However I'm getting a slight issue with a couple of outputs by doing that. On both the {{price}} and {{totalPrice}} its outputting a span...

    <span class="money"> 

around the value in the browser, so what I'm seeing in the actual browser is 

    Total:<span class="money">£60.00</span> 

instead of just 'Total: £60.00'. Any ideas why this is happening?

**Comment by cshold** [comment]
Hm, what's your shop URL I could take a look. Nothing in default Timber has `class="money"` in it. I doubt it, but maybe your money format has that hard coded in there? You can check that on your default settings page.

![screen shot 2015-03-12 at 9 18 25 am](https://cloud.githubusercontent.com/assets/1730309/6618376/c90a3b04-c898-11e4-9764-9ae879ce14a7.png)

**Comment by spring-91** [comment]
Ah, thats what it is, so we added a currency switcher using this tutorial which requires putting that <span> in the currency formatting section in the admin. Is there a way around this so that we can still use the currency switcher and it not output the <span> as text in the browser? 

My shop URL is http://hatch-inc-tester-store.myshopify.com - please excuse the mess, we’re focusing on the functionality and structure before styling etc. 

Thanks for your help so far, appreciate it. 

Best, 

David

**Comment by cshold** [comment]
The fix below is unique to your shop, so this same trick might not work exactly for others. Essentially we're going to change how the money is formatted in JS in two areas so that those spans are not output. It's a hacky solution, but should work for your case.

Around [line 816](https://github.com/Shopify/Timber/blob/master/assets/ajaxify.js.liquid#L816) of ajaxify.js.liquid, add the following new code:
```
var newPrice = Shopify.formatMoney(cartItem.price, settings.moneyFormat).replace('<span class="money">', '').replace('</span>', '');
```
And line 827 from `price: Shopify.formatMoney(cartItem.price, settings.moneyFormat)` to `price: newPrice`.

This will make sure each product's price doesn't have those spans in there.

We'll do something similar to adjust the total cart price. After `$.each` code block, around line 832, add the following:
```
var totalCartPrice = Shopify.formatMoney(cart.total_price, settings.moneyFormat).replace('<span class="money">', '').replace('</span>', '');
```
Then on line 836 change `totalPrice: Shopify.formatMoney(cart.total_price, settings.moneyFormat),` to `totalPrice: totalCartPrice,`

**Comment by spring-91** [comment]
This is exactly what we needed so thank you, really helpful!

Just to be sure as we are building this to be a theme for the theme store, will this cause any issues with regards to that?

Thanks again

**Comment by cshold** [comment]
Honestly not sure. It's not the most attractive solution possible, but given what I know about your implementation a good one. Make sure you test it with multiple currencies and on all required browsers.

**Comment by cshold** [comment]
Hey again, turns out there is a much better solution than what I provided. You can undo those 

Go into `ajax-cart-template.liquid` and change `{{ price }}` to `{{{ price }}}` and `{{ totalPrice }}` to `{{{ totalPrice }}}`. That lets the html be inserted rather than converted to a string like it was before.

**Comment by spring-91** [comment]
Hey Carson, 

Thats such a better solution, thanks for taking the time improve it for me!

**Comment by lesterdefreitas** [comment]
Dudes, this is insane, our client had this exact issue, and this is the exact solution. Don't you love it when that happens. :D Thanks Carson!!

**Comment by cshold** [comment]
:+1:
