### ISSUE TITLE
Keeping render-blocking scripts on the top of page in the template

### ISSUE THREAD

**Issue by peterblazejewicz** [Shopify/Timber#376]
Hi team,

I've been researching subject of scripts blocking rendering in Jekyll/Liquid for other project and I've visited this project (I have a very good opinion about this work). I wonder if you have some reasons behind decision of keeping jQuery and other code in the theme template head section:

https://github.com/Shopify/Timber/blob/master/layout/theme.liquid#L39-L47

Moving part of these scripts (except of modernizr and other head-only scripts) to the page bottom could make shop pages feel snappier:
http://www.shopify.com/partners/blog/18840023-how-to-optimize-themes-for-performance
![20150323212555](https://cloud.githubusercontent.com/assets/14539/6789893/0a321098-d1a4-11e4-83bd-cd095983e80c.jpg)
![20150323212620](https://cloud.githubusercontent.com/assets/14539/6789899/10682dc6-d1a4-11e4-841f-d0f6d4269bcb.jpg)
(oh, and that's just Shopify developer store btw)
Thanks!

**Comment by cshold** [comment]
I'd love to get this JS out of the head as well. Unfortunately right now Shopify themes require some inline JS because of the liquid variables used in some templates. This is most notably seen in the customer templates.

We're experimenting with ways to remove that dependency but don't have anything lined up just yet.

jQuery is in the head because a lot of plugins currently rely on it being loaded before their scripts are, which can happen in the `head` tag. Right now moving it to the footer is on a store-by-store basis, but it's also something we're looking to get a better handle on.

I'm going to close this for now, but know we're constantly looking to improve the performance from a JS, HTML, and CSS standpoints. Cheers.

**Comment by peterblazejewicz** [comment]
@cshold Thanks for great explanation!
