### ISSUE TITLE
Delay in showing Ajaxcart content on first time opening.

### ISSUE THREAD

**Issue by spring-91** [Shopify/Timber#399]
I've noticed there is a delay when you first open the Ajax quick cart, when the quick cart slides into view it takes a moment for the cart content to load in.

Is there a way to fix this so that the content is immediately visible at the first time of revealing the quick cart?

**Comment by cshold** [comment]
Unfortunately not*. With any ajax request, there will be some time needed to load the contents. In our case, we grab the cart contents via ajax and only then can we show the contents. 

* If you want, you can do some custom JS to load the cart contents without opening the drawer on page load. We haven't done this because it increases the page weight and load times.
