### ISSUE TITLE
Add option to have add to cart buttons on collections page

### ISSUE THREAD

**Issue by cshold** [Shopify/Timber#40]
Right now add to cart only works from the product page. Having multiple add to cart buttons on the collections page would be a nice touch too.

**Comment by greatmj** [comment]
I implemented this in the Classic theme. The functionality is dead simple to implement, as @cshold mentioned. However, the theme flips buttons on clicking ("Add to Cart" to "Checkout"), and with this, all buttons flip together on clicking any one of those. It couldn't get around this issue. The best I could do was make separate init calls for each button click instead of a common init. Only the buttons which have been clicked flip now, still a major UI issue. This also results in addition of a It could probably be added as a feature, as a lot of sites now allow adding products on the same page.

**Comment by Cam** [comment]
I personally agree that it would probably be more ideal for the cart ajax to work elegantly with collection page buttons right out of the box, rather than needing any extra customisation.
