### ISSUE TITLE
Ajax cart with custom line item property bug

### ISSUE THREAD

**Issue by alrick** [Shopify/Timber#404]
Hi there!

I've followed this tutorial about adding line item properties to product : 
https://docs.shopify.com/support/your-store/products/how-do-I-collect-additional-information-on-the-product-page-Like-for-a-monogram-engraving-or-customization

The sections "Displaying line item properties on the cart page" and "Removing items from the cart" seem to be already implemented in Timber.

But when I remove a product from the ajax cart (I use Drawer method), all the products are removed even if they have a different line item property.

I've tested directly on the cart page `SHOP_URL/cart` and the remove link is working as expected, this is why I suppose a Timber Ajax cart bug.

Any ideas?
Thanks!

**Comment by cshold** [comment]
Do you have a demo shop I can take a look at?

**Comment by alrick** [comment]
Sure : 
http://tdmdev-2.myshopify.com/products/abebalsa-bl
Password : `merora`

**Comment by cshold** [comment]
Looks like this was missed because of a partial limitation to `/cart/update.js` at the time. The remove link doesn't pass in the `line` parameter, only the product ID - which remains the same when the only difference is a line item property.

To update it, follow these steps:
1. Add `data-line="{{ forloop.index }}"` to the remove button, right after `data-id="{{ item.id }}"` in `cart.liquid`
2. Add `line = el.data('line') || null` after line 962 of `/assets/ajaxify.js`
3. Below that, update `updateQuantity(id, qty);` to `updateQuantity(id, qty, line);`
4. Immediately following that function, change `function updateQuantity(id, qty)` to `function updateQuantity(id, qty, line)`
5. Inside that function, chance `Shopify.changeItem(id, qty, adjustCartCallback);` to `Shopify.changeItem(id, qty, line, adjustCartCallback);`
6. Up at line 223, add in the `line` parameter as follows: `Shopify.changeItem = function(variant_id, quantity, line, callback)`
7. Lastly, add the line parameter to the data set: `data:  'quantity='+quantity+'&id='+variant_id+'&line='+line`

Now the proper line item will be sent when removing the item, rather than all with the same ID.

This is a bit of a complex update, so let me know if you find any new errors and I can help you debug it.

**Comment by alrick** [comment]
Thank you!
I've made the modifications, it's working great except that both disappear with the `.slideUp()` effect, and then one come back at the refresh : 
![cart_remove](https://cloud.githubusercontent.com/assets/1086355/7510774/1a878882-f4a0-11e4-99f2-a358d30cb7f4.gif)

**Comment by cshold** [comment]
Ah so we're close! It closes the row based on the variant ID, which doesn't change per line item. We can fix that by adding `data-line="{{ forloop.index }}"` to `cart__row` in your cart.liquid template. Now we can target a single row at a time by that attribute.

Next, in `updateQuantity` (line 975 of assets/ajaxify.js) change both instances of `[data-id="' + id + '"]` to `[data-line="' + line + '"]`. 

That should be it!

**Comment by alrick** [comment]
Perfect! tyvm

**Comment by grahambarry** [comment]
HERE IS A CHANGELOG FOR THE ajax-cart.js.liquid and the ajax-cart-template.liquid file.
Im sure if you are not using the exact same ajax js cart you could cobble it together out of this solution. 

In the following just search for each line in this document which has a - sign in front of it and change it with the one directly underneath it which has a + sign. Sometimes a blank line is included but you can ignore those and duplicates. 
It works for me.

DOCUMENT
-----------------------------------------------------------------
-------------------------------------------------------------------

Subject: [PATCH] Fix ajax remove function to work with line item properties

---
 assets/ajax-cart.js.liquid         | 33 +++++++++++++++++++--------------
 snippets/ajax-cart-template.liquid | 26 +++++++++++++-------------
 2 files changed, 32 insertions(+), 27 deletions(-)

diff --git a/assets/ajax-cart.js.liquid b/assets/ajax-cart.js.liquid
index 4b4af7b..6756eef 100644
--- a/assets/ajax-cart.js.liquid
+++ b/assets/ajax-cart.js.liquid
@@ -110,11 +110,11 @@ ShopifyAPI.getCart = function(callback) {
 };

 // POST to cart/change.js returns the cart in JSON
-ShopifyAPI.changeItem = function(variant_id, quantity, callback) {
+ShopifyAPI.changeItem = function(variant_id, quantity, line, callback) {
   var params = {
     type: 'POST',
     url: '/cart/change.js',
-    data:  'quantity='+quantity+'&id='+variant_id,
+    data:  'quantity='+quantity+'&id='+variant_id+'&line='+line,
     dataType: 'json',
     success: function(cart) {
       if ((typeof callback) === 'function') {
@@ -255,25 +255,26 @@ var ajaxCart = (function(module, $) {
   removeItem = function(){
     $cartContainer.on('click', '.js-remove-from-cart', function(e){
       var id = $(e.target).attr('data-id');
+      var line = $(e.target).attr('data-line');

-      ShopifyAPI.changeItem(id, 0, function(cart){
+      ShopifyAPI.changeItem(id, 0, line, function(cart){
         var $row = $(e.target).parents('.ajaxcart__product');
         $row.addClass('is-removed');
-
+
         //Make sure the remove item animation is done
         setTimeout(function(){
           cartUpdateCallback(cart);
         }, 500);
-
+
       });
-
+
     });
   };

   buildCart = function (cart) {
     // Start with a fresh cart div
     $cartContainer.empty();
-
+

     // Handlebars.js cart layout
     var items = [],
@@ -311,6 +312,7 @@ var ajaxCart = (function(module, $) {
       // Create item's data object and add to 'items' array
       item = {
         id: cartItem.variant_id,
+        line: index + 1,
         url: cartItem.url,
         img: prodImg,
         name: prodName,
@@ -351,6 +353,7 @@ var ajaxCart = (function(module, $) {
     $body.on('click', '.ajaxcart__qty-adjust', function() {
       var el = $(this),
           id = el.data('id'),
+          line = el.data('line'),
           qtySelector = el.siblings('.ajaxcart__qty-num'),
           qty = parseInt(qtySelector.val().replace(/\D/g, ''));

@@ -367,7 +370,7 @@ var ajaxCart = (function(module, $) {
       // If it has a data-id, update the cart.
       // Otherwise, just update the input's number
       if (id) {
-        updateQuantity(id, qty);
+        updateQuantity(id, qty, line);
       } else {
         qtySelector.val(qty);
       }
@@ -377,13 +380,14 @@ var ajaxCart = (function(module, $) {
     $body.on('change', '.ajaxcart__qty-num', function() {
       var el = $(this),
           id = el.data('id'),
+          line = el.data('line'),
           qty = parseInt(el.val().replace(/\D/g, ''));

       var qty = validateQty(qty);

       // Only update the cart via ajax if we have a variant ID to work with
       if (id) {
-        updateQuantity(id, qty);
+        updateQuantity(id, qty, line);
       }
     });

@@ -482,6 +486,7 @@ var ajaxCart = (function(module, $) {
       $('.js-qty__adjust').on('click', function() {
         var el = $(this),
             id = el.data('id'),
+            line = el.data('line'),
             qtySelector = el.siblings('.js-qty__num'),
             qty = parseInt(qtySelector.val().replace(/\D/g, ''));

@@ -496,7 +501,7 @@ var ajaxCart = (function(module, $) {
         }

         //Update quantity via ajax, without showing the ajaxacrt
-        updateQuantity(id, qty, true);
+        updateQuantity(id, qty, line, true);
         // Update the input's number
         qtySelector.val(qty);
       });
@@ -516,7 +521,7 @@ var ajaxCart = (function(module, $) {
   //Moved updateQuantity into the top-level namespace for this module, so that
   //we can have the ability to update cart total on the cart page via ajax.

-  function updateQuantity(id, qty, disableShowCart) {
+  function updateQuantity(id, qty, line, disableShowCart) {
     // Add activity classes when changing cart quantities
     var row = $('.ajaxcart__row[data-id="' + id + '"]').addClass('is-loading');

@@ -527,12 +532,12 @@ var ajaxCart = (function(module, $) {
     // Slight delay to make sure removed animation is done
     setTimeout(function() {
       if (disableShowCart){
-        ShopifyAPI.changeItem(id, qty);
+        ShopifyAPI.changeItem(id, qty, line);
       }
       else {
-        ShopifyAPI.changeItem(id, qty, adjustCartCallback);
+        ShopifyAPI.changeItem(id, qty, line, adjustCartCallback);
       }
-
+
     }, 250);
   }

diff --git a/snippets/ajax-cart-template.liquid b/snippets/ajax-cart-template.liquid
index f97df07..3954466 100755
--- a/snippets/ajax-cart-template.liquid
+++ b/snippets/ajax-cart-template.liquid
@@ -18,22 +18,22 @@
         {% raw %}
         {{#items}}
         <div class="ajaxcart__product">
-          <div class="ajaxcart__row" data-id="{{id}}">
+          <div class="ajaxcart__row" data-id="{{id}}" data-line="{{line}}">
             <div class="grid">
               <div class="grid__item one-third">
                 <a href="{{url}}" class="ajaxcart__product-image"><img src="{{img}}" alt=""></a>
               </div>
               <div class="grid__item two-thirds table--full-height">
-
+
                 {{!-- We use one <p> tag here because we want the styling of one
                 multi-line paragraph, not three paragraphs.  It keeps our CSS much
-                more consistent to not make custom paragraph rules for the cart.--}}
+                more consistent to not make custom paragraph rules for the cart.--}}

                 <div class='display-table-cell'>
                   <p><a href="{{url}}" class='bold ajaxcart__product-title'>{{name}}</a>
-
+
                   <span class="ajaxcart__product-price">
-                    {{price}}
+                    {{price}}
                     {{#if numerousItems}}
                       <span class='faded'>x {{itemQty}}</span>
                     {{/if}}
@@ -46,7 +46,7 @@
                     <span class="ajaxcart__product-meta">{{ vendor }}</span>
                   {% endraw %}{% endif %}{% raw %}
                   {{#unless variation}}<br>{{/unless}}
-
+
                   {{#if properties}}
                       {{#each properties}}
                         {{@key}}: {{this}}
@@ -58,7 +58,7 @@
                     <br />
                   {{/unless}}

-                  <a class='accent bold pointer js-remove-from-cart' data-id="{{id}}"  href="javascript:void(0);">{% endraw %}{{ 'cart.general.remove' | t}}{% raw %}</a>
+                  <a class='accent bold pointer js-remove-from-cart' data-id="{{id}}" data-line="{{line}}" href="javascript:void(0);">{% endraw %}{{ 'cart.general.remove' | t}}{% raw %}</a>
                   </p>
                 </div>
               </div>
@@ -104,18 +104,18 @@
   <script id="AjaxQty" type="text/template">
   {% raw %}
     <div class="ajaxcart__qty">
-      <button type="button" class="ajaxcart__qty-adjust ajaxcart__qty--minus" data-id="{{id}}" data-qty="{{itemMinus}}">&minus;</button>
-      <input type="text" name="updates[]" class="ajaxcart__qty-num" value="{{itemQty}}" min="0" data-id="{{id}}" aria-label="quantity" pattern="[0-9]*">
-      <button type="button" class="ajaxcart__qty-adjust ajaxcart__qty--plus" data-id="{{id}}" data-qty="{{itemAdd}}">+</button>
+      <button type="button" class="ajaxcart__qty-adjust ajaxcart__qty--minus" data-id="{{id}}" data-line="{{line}}" data-qty="{{itemMinus}}">&minus;</button>
+      <input type="text" name="updates[]" class="ajaxcart__qty-num" value="{{itemQty}}" min="0" data-id="{{id}}" data-line="{{line}}" aria-label="quantity" pattern="[0-9]*">
+      <button type="button" class="ajaxcart__qty-adjust ajaxcart__qty--plus" data-id="{{id}}" data-line="{{line}}" data-qty="{{itemAdd}}">+</button>
     </div>
   {% endraw %}
   </script>
   <script id="JsQty" type="text/template">
   {% raw %}
     <div class="js-qty">
-      <button type="button" class="js-qty__adjust js-qty__adjust--minus" data-id="{{id}}" data-qty="{{itemMinus}}">&minus;</button>
-      <input type="text" class="js-qty__num" value="{{itemQty}}" min="1" data-id="{{id}}" aria-label="quantity" pattern="[0-9]*" name="{{inputName}}" id="{{inputId}}">
-      <button type="button" class="js-qty__adjust js-qty__adjust--plus" data-id="{{id}}" data-qty="{{itemAdd}}">+</button>
<button type="button" class="js-qty__adjust js-qty__adjust--minus" data-id="{{id}}" data-line="{{line}}" data-qty="{{itemMinus}}">&minus;</button>
<input type="text" class="js-qty__num" value="{{itemQty}}" min="1" data-id="{{id}}" data-line="{{line}}" aria-label="quantity" pattern="[0-9]*" name="{{inputName}}" id="{{inputId}}">
<button type="button" class="js-qty__adjust js-qty__adjust--plus" data-id="{{id}}" data-line="{{line}}" data-qty="{{itemAdd}}">+</button>
     </div>
   {% endraw %}
   </script>
--
2.7.4.1.g5468f9e

**Comment by grahambarry** [comment]
HERE IS A CHANGELOG FOR THE ajax-cart.js.liquid and the ajax-cart-template.liquid file.
Im sure if you are not using the exact same ajax js cart you could cobble it together out of this solution.

In the following just search for each line in this document which has a - sign in front of it and change it with the one directly underneath it which has a + sign. Sometimes a blank line is included but you can ignore those and duplicates. 
It works for me.

DOCUMENT
--------------------------------------------------
`From 375860e39dcc7761e53539f3c2cdd44da89ee15c Mon Sep 17 00:00:00 2001
Date: Mon, 12 Sep 2016 11:13:12 -0700
Subject: [PATCH] Fix ajax remove function to work with line item properties

---
 assets/ajax-cart.js.liquid         | 33 +++++++++++++++++++--------------
 snippets/ajax-cart-template.liquid | 26 +++++++++++++-------------
 2 files changed, 32 insertions(+), 27 deletions(-)

diff --git a/assets/ajax-cart.js.liquid b/assets/ajax-cart.js.liquid
index 4b4af7b..6756eef 100644
--- a/assets/ajax-cart.js.liquid
+++ b/assets/ajax-cart.js.liquid
@@ -110,11 +110,11 @@ ShopifyAPI.getCart = function(callback) {
 };

 // POST to cart/change.js returns the cart in JSON
-ShopifyAPI.changeItem = function(variant_id, quantity, callback) {
+ShopifyAPI.changeItem = function(variant_id, quantity, line, callback) {
   var params = {
     type: 'POST',
     url: '/cart/change.js',
-    data:  'quantity='+quantity+'&id='+variant_id,
+    data:  'quantity='+quantity+'&id='+variant_id+'&line='+line,
     dataType: 'json',
     success: function(cart) {
       if ((typeof callback) === 'function') {
@@ -255,25 +255,26 @@ var ajaxCart = (function(module, $) {
   removeItem = function(){
     $cartContainer.on('click', '.js-remove-from-cart', function(e){
       var id = $(e.target).attr('data-id');
+      var line = $(e.target).attr('data-line');

-      ShopifyAPI.changeItem(id, 0, function(cart){
+      ShopifyAPI.changeItem(id, 0, line, function(cart){
         var $row = $(e.target).parents('.ajaxcart__product');
         $row.addClass('is-removed');
-
+
         //Make sure the remove item animation is done
         setTimeout(function(){
           cartUpdateCallback(cart);
         }, 500);
-
+
       });
-
+
     });
   };

   buildCart = function (cart) {
     // Start with a fresh cart div
     $cartContainer.empty();
-
+

     // Handlebars.js cart layout
     var items = [],
@@ -311,6 +312,7 @@ var ajaxCart = (function(module, $) {
       // Create item's data object and add to 'items' array
       item = {
         id: cartItem.variant_id,
+        line: index + 1,
         url: cartItem.url,
         img: prodImg,
         name: prodName,
@@ -351,6 +353,7 @@ var ajaxCart = (function(module, $) {
     $body.on('click', '.ajaxcart__qty-adjust', function() {
       var el = $(this),
           id = el.data('id'),
+          line = el.data('line'),
           qtySelector = el.siblings('.ajaxcart__qty-num'),
           qty = parseInt(qtySelector.val().replace(/\D/g, ''));

@@ -367,7 +370,7 @@ var ajaxCart = (function(module, $) {
       // If it has a data-id, update the cart.
       // Otherwise, just update the input's number
       if (id) {
-        updateQuantity(id, qty);
+        updateQuantity(id, qty, line);
       } else {
         qtySelector.val(qty);
       }
@@ -377,13 +380,14 @@ var ajaxCart = (function(module, $) {
     $body.on('change', '.ajaxcart__qty-num', function() {
       var el = $(this),
           id = el.data('id'),
+          line = el.data('line'),
           qty = parseInt(el.val().replace(/\D/g, ''));

       var qty = validateQty(qty);

       // Only update the cart via ajax if we have a variant ID to work with
       if (id) {
-        updateQuantity(id, qty);
+        updateQuantity(id, qty, line);
       }
     });

@@ -482,6 +486,7 @@ var ajaxCart = (function(module, $) {
       $('.js-qty__adjust').on('click', function() {
         var el = $(this),
             id = el.data('id'),
+            line = el.data('line'),
             qtySelector = el.siblings('.js-qty__num'),
             qty = parseInt(qtySelector.val().replace(/\D/g, ''));

@@ -496,7 +501,7 @@ var ajaxCart = (function(module, $) {
         }

         //Update quantity via ajax, without showing the ajaxacrt
-        updateQuantity(id, qty, true);
+        updateQuantity(id, qty, line, true);
         // Update the input's number
         qtySelector.val(qty);
       });
@@ -516,7 +521,7 @@ var ajaxCart = (function(module, $) {
   //Moved updateQuantity into the top-level namespace for this module, so that
   //we can have the ability to update cart total on the cart page via ajax.

-  function updateQuantity(id, qty, disableShowCart) {
+  function updateQuantity(id, qty, line, disableShowCart) {
     // Add activity classes when changing cart quantities
     var row = $('.ajaxcart__row[data-id="' + id + '"]').addClass('is-loading');

@@ -527,12 +532,12 @@ var ajaxCart = (function(module, $) {
     // Slight delay to make sure removed animation is done
     setTimeout(function() {
       if (disableShowCart){
-        ShopifyAPI.changeItem(id, qty);
+        ShopifyAPI.changeItem(id, qty, line);
       }
       else {
-        ShopifyAPI.changeItem(id, qty, adjustCartCallback);
+        ShopifyAPI.changeItem(id, qty, line, adjustCartCallback);
       }
-
+
     }, 250);
   }

diff --git a/snippets/ajax-cart-template.liquid b/snippets/ajax-cart-template.liquid
index f97df07..3954466 100755
--- a/snippets/ajax-cart-template.liquid
+++ b/snippets/ajax-cart-template.liquid
@@ -18,22 +18,22 @@
         {% raw %}
         {{#items}}
         <div class="ajaxcart__product">
-          <div class="ajaxcart__row" data-id="{{id}}">
+          <div class="ajaxcart__row" data-id="{{id}}" data-line="{{line}}">
             <div class="grid">
               <div class="grid__item one-third">
                 <a href="{{url}}" class="ajaxcart__product-image"><img src="{{img}}" alt=""></a>
               </div>
               <div class="grid__item two-thirds table--full-height">
-
+
                 {{!-- We use one <p> tag here because we want the styling of one
                 multi-line paragraph, not three paragraphs.  It keeps our CSS much
-                more consistent to not make custom paragraph rules for the cart.--}}
+                more consistent to not make custom paragraph rules for the cart.--}}

                 <div class='display-table-cell'>
                   <p><a href="{{url}}" class='bold ajaxcart__product-title'>{{name}}</a>
-
+
                   <span class="ajaxcart__product-price">
-                    {{price}}
+                    {{price}}
                     {{#if numerousItems}}
                       <span class='faded'>x {{itemQty}}</span>
                     {{/if}}
@@ -46,7 +46,7 @@
                     <span class="ajaxcart__product-meta">{{ vendor }}</span>
                   {% endraw %}{% endif %}{% raw %}
                   {{#unless variation}}<br>{{/unless}}
-
+
                   {{#if properties}}
                       {{#each properties}}
                         {{@key}}: {{this}}
@@ -58,7 +58,7 @@
                     <br />
                   {{/unless}}

-                  <a class='accent bold pointer js-remove-from-cart' data-id="{{id}}"  href="javascript:void(0);">{% endraw %}{{ 'cart.general.remove' | t}}{% raw %}</a>
+                  <a class='accent bold pointer js-remove-from-cart' data-id="{{id}}" data-line="{{line}}" href="javascript:void(0);">{% endraw %}{{ 'cart.general.remove' | t}}{% raw %}</a>
                   </p>
                 </div>
               </div>
@@ -104,18 +104,18 @@
   <script id="AjaxQty" type="text/template">
   {% raw %}
     <div class="ajaxcart__qty">
-      <button type="button" class="ajaxcart__qty-adjust ajaxcart__qty--minus" data-id="{{id}}" data-qty="{{itemMinus}}">&minus;</button>
-      <input type="text" name="updates[]" class="ajaxcart__qty-num" value="{{itemQty}}" min="0" data-id="{{id}}" aria-label="quantity" pattern="[0-9]*">
-      <button type="button" class="ajaxcart__qty-adjust ajaxcart__qty--plus" data-id="{{id}}" data-qty="{{itemAdd}}">+</button>
+      <button type="button" class="ajaxcart__qty-adjust ajaxcart__qty--minus" data-id="{{id}}" data-line="{{line}}" data-qty="{{itemMinus}}">&minus;</button>
+      <input type="text" name="updates[]" class="ajaxcart__qty-num" value="{{itemQty}}" min="0" data-id="{{id}}" data-line="{{line}}" aria-label="quantity" pattern="[0-9]*">
+      <button type="button" class="ajaxcart__qty-adjust ajaxcart__qty--plus" data-id="{{id}}" data-line="{{line}}" data-qty="{{itemAdd}}">+</button>
     </div>
   {% endraw %}
   </script>
   <script id="JsQty" type="text/template">
   {% raw %}
     <div class="js-qty">
-      <button type="button" class="js-qty__adjust js-qty__adjust--minus" data-id="{{id}}" data-qty="{{itemMinus}}">&minus;</button>
-      <input type="text" class="js-qty__num" value="{{itemQty}}" min="1" data-id="{{id}}" aria-label="quantity" pattern="[0-9]*" name="{{inputName}}" id="{{inputId}}">
-      <button type="button" class="js-qty__adjust js-qty__adjust--plus" data-id="{{id}}" data-qty="{{itemAdd}}">+</button>
<button type="button" class="js-qty__adjust js-qty__adjust--minus" data-id="{{id}}" data-line="{{line}}" data-qty="{{itemMinus}}">&minus;</button>
<input type="text" class="js-qty__num" value="{{itemQty}}" min="1" data-id="{{id}}" data-line="{{line}}" aria-label="quantity" pattern="[0-9]*" name="{{inputName}}" id="{{inputId}}">
<button type="button" class="js-qty__adjust js-qty__adjust--plus" data-id="{{id}}" data-line="{{line}}" data-qty="{{itemAdd}}">+</button>
     </div>
   {% endraw %}
   </script>
--
2.7.4.1.g5468f9e
`

**Comment by grahambarry** [comment]
Here is a changelog to edit ajax-cart.js.liquid and ajax-cart-template.liquid in order to fix the remove all similar items despite them being unique through line item properties.

Wherever it has a minus sign on a line replace with the plus sign directly underneath. It works for me. :)
[Ajax Cart Patch Diff.txt](https://github.com/Shopify/Timber/files/474921/Ajax.Cart.Patch.Diff.txt)
