### ISSUE TITLE
Scrolling still enabled when drawer is open on IOS mobile?

### ISSUE THREAD

**Issue by spring-91** [Shopify/Timber#457]
I seem to be having some trouble with my drawers on IOS in that when the drawer is open the content outside the drawer is still scrollable. I thought it was just happening for me but when I looked at the demo it seems to be happening there for the cart drawer. My issue is with my mobile nav drawer & cart drawer.

I'm not great with JS but is this line preventing the scrolling of content outside the drawer when its open?

```
// Lock scrolling on mobile
    this.$nodes.page.on('touchmove.drawer', function () {
      return false;
    });
```

After doing some research online I'm not sure IOS responds to overflow:hidden on the body and Im struggling to find a solution as the only thing I have found is to apply position:fixed to js-drawer-open but when the drawer is toggled it makes everything jump to the top of the screen.

```
.js-drawer-open {
    height: 100%;
    overflow: hidden;
    width: 100%;
    position: fixed;
 }
```

I wondered if there was a simple solution to this that I'm missing? I'm not sure if this is just an issue I have created or something that was already there?

If you have any advice or this is something you can help with I would be most grateful.

**Comment by cshold** [comment]
We worked for a while trying to get it working as you expect on iOS, but as mentioned, `overflow: hidden` doesn't work like it does on the majority of other browsers and devices. Instead of opting to create a workaround that would be hacky at best, we decided to let the iOS scrolling behaviour stick around. It doesn't detract from the user's experience, as at worst they lose their position on a single page.
