### ISSUE TITLE
Preorder item cannot be removed from ajax cart

### ISSUE THREAD

**Issue by JennyM88** [Shopify/Timber#465]
We have recently added a plugin (Preorder By SpurIT) to preorder an item from our store but it becomes glitchy when trying to remove from the cart see:

http://screencast.com/t/ogIRAA9LjAN

This issue only seems to occur on IE (I'm on 11). I have spoken to the plugin developers and they say the below:

'This is theme's specific problem and it is not related to the app. So you need to check how your Ajax Cart is working in your theme. Pre-Order item differs from regular item because it has line item properties. Perhaps such products are handled by your ajax cart in not stable way. '

Could anyone please advise?

**Comment by cshold** [comment]
This would better fit the [Shopify Forums](https://ecommerce.shopify.com/c/ecommerce-design) or by reaching out to [our gurus](https://docs.shopify.com/support), since this is specific to your customized theme and not the Timber framework.

I did a quick test and items are removed from the cart as expected, so not even quite sure where the issue lies.
