### ISSUE TITLE
Timber Navigation Slidedown

### ISSUE THREAD

**Issue by marshall993** [Shopify/Timber#474]
Hi I am having trouble implementing the slideDown function to the timber menu how can I achieve this:

function showDropdown ($el) {
    $el.slideDown(1000);
    setTimeout(function() {
      timber.cache.$body.on('touchstart', function() {
        hideDropdown($el);
      });
    }, 250);
  }

**Comment by cshold** [comment]
The current set adds a class to `.site-nav--has-dropdown`. Using `slideDown` on that won't do anything because it's already visible. You want to set it on the child inside of that. Do that with `$el.find('.site-nav__dropdown').slideDown(1000);`

You'll have to do the same in the `hideDropdown` method.

**Comment by Cam** [comment]
And here I was doing this with CSS :P

**Comment by cshold** [comment]
CSS is my preferred method too, though depending on how much the dropdown heights will vary it can be challenging. Lately I've found an opacity and translateY have been great in all situations.

**Comment by marshall993** [comment]
You da man thanks!
