### ISSUE TITLE
Using a fixed header with drawers

### ISSUE THREAD

**Issue by shoshanna** [Shopify/Timber#537]
I'm making a site with a fixed header. This wasn't working because having fixed content conflicted with translateX on is-moved-by-drawer.

I seem to have solved this by moving my header to its own fixed wrapper. I also changed PageContainer to a class instead of ID in timber.js.liquid so that both the header and the content can have that class. Like this:

```
<div class="fixed-header">
    <div class="PageContainer is-moved-by-drawer">
    	This is the fixed header content.
	</div>
</div>

<div class="PageContainer is-moved-by-drawer">
	This is the page content.
</div>

```

This seems to be working, but I'm not 100% confident that there isn't any hidden issue with the drawers JS that I'm missing.

Are there any examples out there of implementations with a fixed header that I can compare with? Do any immediate problems with my solution jump out?

Thanks!

**Comment by cshold** [comment]
Hey Shoshanna, I wouldn't recommend using a fixed header with a drawer pattern. We've tried it a few times in themes — even on Shopify.com for a while — but it caused quite a few headaches trying to get right. Browsers and mobile devices have a tough time with it, the main issue being translating/shifting a fixed element because they are relative to the window.

My suggestion would be to turn off the `PageContainer` translation and simply have the drawer overlap the page content. That way you don't have to try and move the fixed header at the same time. The performance will be smoother and you'll have less trouble getting the fixed header to stay visible.

Your approach is on the right track though if you do choose to go down this route. You have to move both elements themselves, although differently in the CSS. The `PageContainer` wrapper an use `translate` while the fixed header will need to update it's `left` position, as you [can't translate a fixed element with much success](http://stackoverflow.com/questions/15194313/webkit-css-transform3d-position-fixed-issue).

**Comment by shoshanna** [comment]
Aha, in that case just letting it overlap does seem like the best solution. I moved everything back the way it was and removed is-moved-by-drawer from the page content, so this:
`<div id="PageContainer" class="is-moved-by-drawer">`
became this:
`<div id="PageContainer">`

I also changed the height on .js-drawer-open because when I opened the menu from the fixed header it was jumping to the top of the page. I changed this:

```
.js-drawer-open {
  height: 100%;
}
```
to this:
```
.js-drawer-open {
  height: auto; 
}
```

So hopefully that's the fix. 

Thanks so much for your advice!

**Comment by Panoply** [comment]
Fixed headers are a necessity in 2016 and wherever there's a will, there's a way. You will need to tweak your timber file and structure and if you're going to do that begin by splitting up you layout into more manageable sections and logical chunks. In essence, you modularize the layout. I'm using a sticky fixed heading on a current project i'm working on  (+ several other additional components, which include basket.js & jquery-pjax). In mobile, simply turn it off using media queries. 

Some important things to note here. You cannot nest childs within the `.is-moved-by-drawer` class, if you do, you will have issues like the page scrolling to top when opening the cart  and if you're running chrome  `position: fixed;`  will fail due to `translateZ `css3 transition (see [here](http://stackoverflow.com/questions/2637058/positions-fixed-doesnt-work-when-using-webkit-transform) for further reading on that). You can also, if you don't want to break the framework apart and not to concerned about a `max-width` apply a  `position:absolute;` to `.js-drawer-open` + little bit of javascript. 

For some better reference, see my below theme layout structure:

```
<body id="{{ page_title | handle }}" class="{% if customer %}customer-logged-in {% endif %}template-{{ template | replace: '.', ' ' | truncatewords: 1, '' | handle }}">

  <!-- Drawers :: Include Drawers -->
  {% include 'layout--drawer-nav' %}
  {% include 'layout--drawer-cart' %}

  <!-- Container :: Page Container -->
  <div id="container">

    <!-- Header :: Head Elements -->
    <header role="banner">
      {% include 'layout--header' %}
    </header>

    <!-- Main Menu :: Desktop Navigation -->
    <nav role="navigation">
      {% include 'layout--navbar' %}
    </nav>

    <!-- Main :: Template Content -->
    <main role="main" class="is-moved-by-drawer" data-pjax-container>

      <!-- Data :: Dormant Element  -->
      <div class="wrapper">
        {{ content_for_layout }}
      </div>

      <!-- Pjax Initialise :: PushState + Ajax -->
      {% include 'js--inline' %}
    </main>

    <!-- Footer :: Base Element -->
    <footer>
      {% include 'layout--footer'%}
    </footer>
  </div>

  <!-- Cart :: Initialize Ajax Cart (init) -->
  <script>
    jQuery(function($) {
      ajaxCart.init({
        formSelector: '#AddToCartForm',
        cartContainer: '#CartContainer',
        addToCartSelector: '#AddToCart',
        cartCountSelector: '#CartCount',
        cartCostSelector: '#CartCost',
        moneyFormat: {{ shop.money_format | json }}
      });
    });
    jQuery('body').on('ajaxCart.afterCartLoad', function(evt, cart) {
      timber.RightDrawer.open();
    });
  </script>

  <!-- Currencies :: Shopify Asset -->
  <script>
    basket
    .require({
      url: '//cdn.shopify.com/s/javascripts/currencies.js',
      key: 'cdn.shopify-currencies'
    },{
      url: '{{ 'currencies.js' | asset_url  }}',
      skipCache: true 
    });
  </script>
  {% include 'js--cart-template' %}
</body>
```

<img width="1436" alt="screen shot 2016-05-17 at 08 23 08" src="https://cloud.githubusercontent.com/assets/7041324/15313024/b28edc62-1c08-11e6-856d-5d47c1b02f17.png">

**Comment by ButsAndCats** [comment]
I think this is related to chrome not being able to render position:fixed on elements under a transformation. Therefore a quick fix can be implemented by not transforming the page-container. You want your css output to be something like this:

```
.is-moved-by-drawer {
    /* -webkit-transform: translateZ(0); */ Remove this 
    /* will-change: transform; */ and this
    transition: all 0.4s cubic-bezier(0.46, 0.01, 0.32, 1);
}

.js-drawer-open-right .is-moved-by-drawer {
    /*-ms-transform: translateX(-300px); */ and these.
    /* -webkit-transform: translateX(-300px); */
    /* transform: translateX(-300px); */
}
```
Of course doing so will mean that your whole page won't move left on drawer open. Personally I was happy to make this sacrifice. Just increased the z-index of the drawer to ensure it was higher than the fixed header.
